# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-15 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='code',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
    ]
